// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BoltPb.proto

package com.bolttest.server;

public final class BoltProto {
  private BoltProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BoltPbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pojo.BoltPb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string devId = 2;</code>
     * @return The devId.
     */
    String getDevId();
    /**
     * <code>string devId = 2;</code>
     * @return The bytes for devId.
     */
    com.google.protobuf.ByteString
        getDevIdBytes();

    /**
     * <code>bool conn = 3;</code>
     * @return The conn.
     */
    boolean getConn();
  }
  /**
   * Protobuf type {@code pojo.BoltPb}
   */
  public static final class BoltPb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pojo.BoltPb)
      BoltPbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BoltPb.newBuilder() to construct.
    private BoltPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BoltPb() {
      devId_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new BoltPb();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BoltPb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              devId_ = s;
              break;
            }
            case 24: {

              conn_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bolttest.server.BoltProto.internal_static_pojo_BoltPb_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bolttest.server.BoltProto.internal_static_pojo_BoltPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BoltPb.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }

    public static final int DEVID_FIELD_NUMBER = 2;
    private volatile Object devId_;
    /**
     * <code>string devId = 2;</code>
     * @return The devId.
     */
    @Override
    public String getDevId() {
      Object ref = devId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        devId_ = s;
        return s;
      }
    }
    /**
     * <code>string devId = 2;</code>
     * @return The bytes for devId.
     */
    @Override
    public com.google.protobuf.ByteString
        getDevIdBytes() {
      Object ref = devId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        devId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONN_FIELD_NUMBER = 3;
    private boolean conn_;
    /**
     * <code>bool conn = 3;</code>
     * @return The conn.
     */
    @Override
    public boolean getConn() {
      return conn_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getDevIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, devId_);
      }
      if (conn_ != false) {
        output.writeBool(3, conn_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getDevIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, devId_);
      }
      if (conn_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, conn_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BoltPb)) {
        return super.equals(obj);
      }
      BoltPb other = (BoltPb) obj;

      if (getId()
          != other.getId()) return false;
      if (!getDevId()
          .equals(other.getDevId())) return false;
      if (getConn()
          != other.getConn()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + DEVID_FIELD_NUMBER;
      hash = (53 * hash) + getDevId().hashCode();
      hash = (37 * hash) + CONN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getConn());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BoltPb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BoltPb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BoltPb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BoltPb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BoltPb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BoltPb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BoltPb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BoltPb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BoltPb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BoltPb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BoltPb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BoltPb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BoltPb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pojo.BoltPb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pojo.BoltPb)
        BoltPbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bolttest.server.BoltProto.internal_static_pojo_BoltPb_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bolttest.server.BoltProto.internal_static_pojo_BoltPb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BoltPb.class, Builder.class);
      }

      // Construct using com.bolttest.server.BoltProto.BoltPb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        devId_ = "";

        conn_ = false;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bolttest.server.BoltProto.internal_static_pojo_BoltPb_descriptor;
      }

      @Override
      public BoltPb getDefaultInstanceForType() {
        return BoltPb.getDefaultInstance();
      }

      @Override
      public BoltPb build() {
        BoltPb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public BoltPb buildPartial() {
        BoltPb result = new BoltPb(this);
        result.id_ = id_;
        result.devId_ = devId_;
        result.conn_ = conn_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BoltPb) {
          return mergeFrom((BoltPb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BoltPb other) {
        if (other == BoltPb.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getDevId().isEmpty()) {
          devId_ = other.devId_;
          onChanged();
        }
        if (other.getConn() != false) {
          setConn(other.getConn());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BoltPb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BoltPb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {

        id_ = 0L;
        onChanged();
        return this;
      }

      private Object devId_ = "";
      /**
       * <code>string devId = 2;</code>
       * @return The devId.
       */
      public String getDevId() {
        Object ref = devId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          devId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string devId = 2;</code>
       * @return The bytes for devId.
       */
      public com.google.protobuf.ByteString
          getDevIdBytes() {
        Object ref = devId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          devId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string devId = 2;</code>
       * @param value The devId to set.
       * @return This builder for chaining.
       */
      public Builder setDevId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        devId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string devId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDevId() {

        devId_ = getDefaultInstance().getDevId();
        onChanged();
        return this;
      }
      /**
       * <code>string devId = 2;</code>
       * @param value The bytes for devId to set.
       * @return This builder for chaining.
       */
      public Builder setDevIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        devId_ = value;
        onChanged();
        return this;
      }

      private boolean conn_ ;
      /**
       * <code>bool conn = 3;</code>
       * @return The conn.
       */
      @Override
      public boolean getConn() {
        return conn_;
      }
      /**
       * <code>bool conn = 3;</code>
       * @param value The conn to set.
       * @return This builder for chaining.
       */
      public Builder setConn(boolean value) {

        conn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool conn = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearConn() {

        conn_ = false;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pojo.BoltPb)
    }

    // @@protoc_insertion_point(class_scope:pojo.BoltPb)
    private static final BoltPb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BoltPb();
    }

    public static BoltPb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BoltPb>
        PARSER = new com.google.protobuf.AbstractParser<BoltPb>() {
      @Override
      public BoltPb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BoltPb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BoltPb> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BoltPb> getParserForType() {
      return PARSER;
    }

    @Override
    public BoltPb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BoltPbArrPbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pojo.BoltPbArrPb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .pojo.BoltPb arr = 1;</code>
     */
    java.util.List<BoltPb>
        getArrList();
    /**
     * <code>repeated .pojo.BoltPb arr = 1;</code>
     */
    BoltPb getArr(int index);
    /**
     * <code>repeated .pojo.BoltPb arr = 1;</code>
     */
    int getArrCount();
    /**
     * <code>repeated .pojo.BoltPb arr = 1;</code>
     */
    java.util.List<? extends BoltPbOrBuilder>
        getArrOrBuilderList();
    /**
     * <code>repeated .pojo.BoltPb arr = 1;</code>
     */
    BoltPbOrBuilder getArrOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code pojo.BoltPbArrPb}
   */
  public static final class BoltPbArrPb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pojo.BoltPbArrPb)
      BoltPbArrPbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BoltPbArrPb.newBuilder() to construct.
    private BoltPbArrPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BoltPbArrPb() {
      arr_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new BoltPbArrPb();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BoltPbArrPb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                arr_ = new java.util.ArrayList<BoltPb>();
                mutable_bitField0_ |= 0x00000001;
              }
              arr_.add(
                  input.readMessage(BoltPb.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          arr_ = java.util.Collections.unmodifiableList(arr_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bolttest.server.BoltProto.internal_static_pojo_BoltPbArrPb_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bolttest.server.BoltProto.internal_static_pojo_BoltPbArrPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BoltPbArrPb.class, Builder.class);
    }

    public static final int ARR_FIELD_NUMBER = 1;
    private java.util.List<BoltPb> arr_;
    /**
     * <code>repeated .pojo.BoltPb arr = 1;</code>
     */
    @Override
    public java.util.List<BoltPb> getArrList() {
      return arr_;
    }
    /**
     * <code>repeated .pojo.BoltPb arr = 1;</code>
     */
    @Override
    public java.util.List<? extends BoltPbOrBuilder>
        getArrOrBuilderList() {
      return arr_;
    }
    /**
     * <code>repeated .pojo.BoltPb arr = 1;</code>
     */
    @Override
    public int getArrCount() {
      return arr_.size();
    }
    /**
     * <code>repeated .pojo.BoltPb arr = 1;</code>
     */
    @Override
    public BoltPb getArr(int index) {
      return arr_.get(index);
    }
    /**
     * <code>repeated .pojo.BoltPb arr = 1;</code>
     */
    @Override
    public BoltPbOrBuilder getArrOrBuilder(
        int index) {
      return arr_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < arr_.size(); i++) {
        output.writeMessage(1, arr_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < arr_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, arr_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BoltPbArrPb)) {
        return super.equals(obj);
      }
      BoltPbArrPb other = (BoltPbArrPb) obj;

      if (!getArrList()
          .equals(other.getArrList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getArrCount() > 0) {
        hash = (37 * hash) + ARR_FIELD_NUMBER;
        hash = (53 * hash) + getArrList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BoltPbArrPb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BoltPbArrPb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BoltPbArrPb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BoltPbArrPb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BoltPbArrPb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BoltPbArrPb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BoltPbArrPb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BoltPbArrPb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BoltPbArrPb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BoltPbArrPb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BoltPbArrPb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BoltPbArrPb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BoltPbArrPb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pojo.BoltPbArrPb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pojo.BoltPbArrPb)
        BoltPbArrPbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bolttest.server.BoltProto.internal_static_pojo_BoltPbArrPb_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bolttest.server.BoltProto.internal_static_pojo_BoltPbArrPb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BoltPbArrPb.class, Builder.class);
      }

      // Construct using com.bolttest.server.BoltProto.BoltPbArrPb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getArrFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (arrBuilder_ == null) {
          arr_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          arrBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bolttest.server.BoltProto.internal_static_pojo_BoltPbArrPb_descriptor;
      }

      @Override
      public BoltPbArrPb getDefaultInstanceForType() {
        return BoltPbArrPb.getDefaultInstance();
      }

      @Override
      public BoltPbArrPb build() {
        BoltPbArrPb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public BoltPbArrPb buildPartial() {
        BoltPbArrPb result = new BoltPbArrPb(this);
        int from_bitField0_ = bitField0_;
        if (arrBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            arr_ = java.util.Collections.unmodifiableList(arr_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.arr_ = arr_;
        } else {
          result.arr_ = arrBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BoltPbArrPb) {
          return mergeFrom((BoltPbArrPb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BoltPbArrPb other) {
        if (other == BoltPbArrPb.getDefaultInstance()) return this;
        if (arrBuilder_ == null) {
          if (!other.arr_.isEmpty()) {
            if (arr_.isEmpty()) {
              arr_ = other.arr_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureArrIsMutable();
              arr_.addAll(other.arr_);
            }
            onChanged();
          }
        } else {
          if (!other.arr_.isEmpty()) {
            if (arrBuilder_.isEmpty()) {
              arrBuilder_.dispose();
              arrBuilder_ = null;
              arr_ = other.arr_;
              bitField0_ = (bitField0_ & ~0x00000001);
              arrBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getArrFieldBuilder() : null;
            } else {
              arrBuilder_.addAllMessages(other.arr_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BoltPbArrPb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BoltPbArrPb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<BoltPb> arr_ =
        java.util.Collections.emptyList();
      private void ensureArrIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          arr_ = new java.util.ArrayList<BoltPb>(arr_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          BoltPb, BoltPb.Builder, BoltPbOrBuilder> arrBuilder_;

      /**
       * <code>repeated .pojo.BoltPb arr = 1;</code>
       */
      public java.util.List<BoltPb> getArrList() {
        if (arrBuilder_ == null) {
          return java.util.Collections.unmodifiableList(arr_);
        } else {
          return arrBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pojo.BoltPb arr = 1;</code>
       */
      public int getArrCount() {
        if (arrBuilder_ == null) {
          return arr_.size();
        } else {
          return arrBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pojo.BoltPb arr = 1;</code>
       */
      public BoltPb getArr(int index) {
        if (arrBuilder_ == null) {
          return arr_.get(index);
        } else {
          return arrBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pojo.BoltPb arr = 1;</code>
       */
      public Builder setArr(
          int index, BoltPb value) {
        if (arrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrIsMutable();
          arr_.set(index, value);
          onChanged();
        } else {
          arrBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pojo.BoltPb arr = 1;</code>
       */
      public Builder setArr(
          int index, BoltPb.Builder builderForValue) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          arr_.set(index, builderForValue.build());
          onChanged();
        } else {
          arrBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pojo.BoltPb arr = 1;</code>
       */
      public Builder addArr(BoltPb value) {
        if (arrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrIsMutable();
          arr_.add(value);
          onChanged();
        } else {
          arrBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pojo.BoltPb arr = 1;</code>
       */
      public Builder addArr(
          int index, BoltPb value) {
        if (arrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrIsMutable();
          arr_.add(index, value);
          onChanged();
        } else {
          arrBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pojo.BoltPb arr = 1;</code>
       */
      public Builder addArr(
          BoltPb.Builder builderForValue) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          arr_.add(builderForValue.build());
          onChanged();
        } else {
          arrBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pojo.BoltPb arr = 1;</code>
       */
      public Builder addArr(
          int index, BoltPb.Builder builderForValue) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          arr_.add(index, builderForValue.build());
          onChanged();
        } else {
          arrBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pojo.BoltPb arr = 1;</code>
       */
      public Builder addAllArr(
          Iterable<? extends BoltPb> values) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, arr_);
          onChanged();
        } else {
          arrBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pojo.BoltPb arr = 1;</code>
       */
      public Builder clearArr() {
        if (arrBuilder_ == null) {
          arr_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          arrBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pojo.BoltPb arr = 1;</code>
       */
      public Builder removeArr(int index) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          arr_.remove(index);
          onChanged();
        } else {
          arrBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pojo.BoltPb arr = 1;</code>
       */
      public BoltPb.Builder getArrBuilder(
          int index) {
        return getArrFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pojo.BoltPb arr = 1;</code>
       */
      public BoltPbOrBuilder getArrOrBuilder(
          int index) {
        if (arrBuilder_ == null) {
          return arr_.get(index);  } else {
          return arrBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pojo.BoltPb arr = 1;</code>
       */
      public java.util.List<? extends BoltPbOrBuilder>
           getArrOrBuilderList() {
        if (arrBuilder_ != null) {
          return arrBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(arr_);
        }
      }
      /**
       * <code>repeated .pojo.BoltPb arr = 1;</code>
       */
      public BoltPb.Builder addArrBuilder() {
        return getArrFieldBuilder().addBuilder(
            BoltPb.getDefaultInstance());
      }
      /**
       * <code>repeated .pojo.BoltPb arr = 1;</code>
       */
      public BoltPb.Builder addArrBuilder(
          int index) {
        return getArrFieldBuilder().addBuilder(
            index, BoltPb.getDefaultInstance());
      }
      /**
       * <code>repeated .pojo.BoltPb arr = 1;</code>
       */
      public java.util.List<BoltPb.Builder>
           getArrBuilderList() {
        return getArrFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          BoltPb, BoltPb.Builder, BoltPbOrBuilder>
          getArrFieldBuilder() {
        if (arrBuilder_ == null) {
          arrBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              BoltPb, BoltPb.Builder, BoltPbOrBuilder>(
                  arr_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          arr_ = null;
        }
        return arrBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pojo.BoltPbArrPb)
    }

    // @@protoc_insertion_point(class_scope:pojo.BoltPbArrPb)
    private static final BoltPbArrPb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BoltPbArrPb();
    }

    public static BoltPbArrPb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BoltPbArrPb>
        PARSER = new com.google.protobuf.AbstractParser<BoltPbArrPb>() {
      @Override
      public BoltPbArrPb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BoltPbArrPb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BoltPbArrPb> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BoltPbArrPb> getParserForType() {
      return PARSER;
    }

    @Override
    public BoltPbArrPb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pojo_BoltPb_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pojo_BoltPb_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pojo_BoltPbArrPb_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pojo_BoltPbArrPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014BoltPb.proto\022\004pojo\"1\n\006BoltPb\022\n\n\002id\030\001 \001" +
      "(\003\022\r\n\005devId\030\002 \001(\t\022\014\n\004conn\030\003 \001(\010\"(\n\013BoltP" +
      "bArrPb\022\031\n\003arr\030\001 \003(\0132\014.pojo.BoltPbB;\n.com" +
      ".csg.grc.graphserver.service.neo4j.proto" +
      "bufB\tBoltProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pojo_BoltPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pojo_BoltPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pojo_BoltPb_descriptor,
        new String[] { "Id", "DevId", "Conn", });
    internal_static_pojo_BoltPbArrPb_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pojo_BoltPbArrPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pojo_BoltPbArrPb_descriptor,
        new String[] { "Arr", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
